### ISSUE TITLE
The Config's "new_relative_path_name" is ignored

### ISSUE THREAD

**Issue by Arparso** [4c0d3r/namer#5]
The config key "new_relative_path_name" appears to get ignored. It always defaults back to "{site} - {date} - {name}/{site} - {date} - {name}.{ext}".

Seems like it is trying to read from the wrong section [metadata] instead of [watchdog]:

https://github.com/4c0d3r/namer/blob/cba94b745ab070915a9a66cde9d38dc5bdfcf54e/namer_types.py#L315-L316

**Comment by 4c0d3r** [comment]
Resolved with tests:

https://github.com/4c0d3r/namer/commit/b34925caeff56a351f9ebfccb19e0104319ed62b
 With a fix for windows :(
https://github.com/4c0d3r/namer/commit/b34925caeff56a351f9ebfccb19e0104319ed62b

Thanks for the great bug report.
